# Build settings
incremental: true

# Site settings
title: Elias Meire
description: "Personal website of Elias Meire"
author: Elias Meire
email: me@eliasmei.re
github_username: eliasmeire
primary_color: '#212121'

collections:
  favicon:
    output: true
    permalink: /

compress_html:
  comments: all
  clippings: all

exclude:
  - README.md
  - package.json
  - gulpfile.js
  - build.sh